<a href="https://colab.research.google.com/github/Sehajbirsingh/Math-LAB-for-ML/blob/main/Lab_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [2]:
# importing numpy
import numpy as np

In [4]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
array = np.array([1, 2, 3, 5, 0])
print(array)
print(np.all(array))

[1 2 3 5 0]
False


In [5]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
array = np.array([3, -1, 3, 7, 2])
print(array)
print(np.any(array))

[ 3 -1  3  7  2]
True


In [6]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
array = np.array([0, 0, 0, 0])
print(array)
print(np.any(array))

[0 0 0 0]
False


In [7]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
array = np.array([56, -2, 7])
print(array)
print(array.nbytes)

[56 -2  7]
24


In [10]:
# Create a numpy array with 10 zeros and print the array.
array = np.zeros(10,dtype=int)
print(array)


# Create a numpy array with 6 ones and print the array.
array = np.ones(6,dtype=int)
print(array)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
array = np.full(12, 3)
print(array)



[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [11]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
array = np.arange(8, 21)
print(array)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
array = np.arange(8, 21, 2)
print(array)


[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [13]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
array = np.random.normal(2, 0.5, 100)
print(np.mean(array))
print(np.max(array))
print(np.min(array))
print(np.std(array))

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
array = np.random.normal(2, 0.5, 1000)
print(np.mean(array))
print(np.max(array))
print(np.min(array))
print(np.std(array))

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
array = np.random.normal(2, 0.5, 1000000)
print(np.mean(array))
print(np.max(array))
print(np.min(array))
print(np.std(array))

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?


1.9936593858918379
3.1373712138154017
0.6899794228251845
0.54019410852423
2.0051620465795668
3.4404757922968336
0.4756526976265887
0.47958780715358995
1.9996564749567498
4.563641536164711
-0.34996681204907265
0.49983823299089986
